### ISSUE TITLE
RC [Code Compiler] JS Functionality has not been tested.

### ISSUE THREAD

**Issue by EriktheRDev** [B-Kernel/bkernel#24]
I've tested PY functionality and it works. However, I do not currently have a JavaScript extension to test out that functionality yet. I know @arnavthorat78 has JS, so I really want to see if that could potentially work or not.

**Comment by arnavthorat78** [comment]
Running Node.js code inside of Python is a tricky and inconsistent process between operating systems. 

Also, the file must be executable, otherwise it will throw an error. 

See this [Stack Overflow](https://stackoverflow.com/questions/62862861/running-nodejs-from-python) fourm for more information.

**Comment by arnavthorat78** [comment]
The code has been added; I defied the laws of programming!
